### ISSUE TITLE
SQL injections kan fortsatt se

### ISSUE THREAD

**Issue by andwaal** [SivertRanden/compliance-web-app#1]
Hei
Ser at dere har jobbet med å sikre mot SQL-injections d56ea760bdd4ea834ca5d86bd9eb3ea735aedcbb
Her har dere brukt _inject()_ for å escape inputen(?), dette tror jeg ikke hjelper/holder.

Derimot så er dette allerede tenkte på i sqlite biblioteket dere benytter. 
Dette er beskrevet [her](https://github.com/mapbox/node-sqlite3/wiki/API#databaserunsql-param--callback), men gisten er at istedet for å concate query manuelt slik som dette:

```
db.get("SELECT * FROM answer WHERE id_answer = " + escape(id), (err, row) => {
```

så kan dere skrive
```
db.get("SELECT * FROM answer WHERE id_answer ?", [id], (err, row) => {
```

Ps. linket commit over legger også til _mysql_ som referanse i prosjektet.

**Comment by OivindBirk** [comment]
Hei.

Escaping SQL injections er nå implementert ved bruk av SQLite-biblioteket og [id].
Takk for kommentaren 👍
